version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: digipay-wallet-postgres
    environment:
      POSTGRES_DB: digipay_wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - digipay-network

  api:
    build:
      context: .
      dockerfile: DigiPay.Wallet.Api/Dockerfile
    container_name: digipay-wallet-api
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=digipay_wallet;Username=postgres;Password=postgres;CommandTimeout=120
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - digipay-network

volumes:
  postgres-data:
    name: digipay-wallet-postgres-data

networks:
  digipay-network:
    name: digipay-network 